name: Retraining Recommendation Model

on:
  schedule:
    - cron: '30 18 * * *' 
  workflow_dispatch:      
jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Retraining_Requirements.txt
    - name: Run Retraining Script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python Retraining_Recommendation_Models.py
